### ISSUE TITLE
Theme dropdown will have double the amount of Themes 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#261]
**Issue:** Seems to be on Windows only. I had this issue a single time with MacOS but then was fixed in a matter of minutes and couldnt replicate again after that. 

- first issue is the list of themes are duplicated when you open the dropdown 

-The second issue is the names of the themes are showing the path instead of just the name of the theme. Example (Themes \ default )

- Default will also appear twice in the dropdown once as "Default" the second as "Themes \ Default" 

-And I'm not sure if this part really matters or not but I noticed I have 2 folders labeled Theme one of them in 

`Uplink/ui/extra/themes` 

and also 

`.uplink/themes`

**So during the call Sheldon and I had he noticed in `mod.rs ui/src/utils` the code, line 18 `-join(path: ".uplink/"` was searching for .uplink and inside the folder we had a Themes folder and then a list of the themes as well so thats why in Settings the User would still have a duplicated list of themes

**Screenshot:**

![image](https://user-images.githubusercontent.com/93608357/217084147-1a8a820e-cfe3-4899-8dd6-b7b114d46c51.png)

Themes & Themes \ Default 

https://user-images.githubusercontent.com/93608357/217906000-53bb526d-7501-448d-8e7a-d03235b575d9.mp4

![image](https://user-images.githubusercontent.com/93608357/217914505-c6007714-b207-47bf-a239-4ad650ff9f2f.png)

**Comment by phillsatellite** [comment]
@tooshel this is fixed on my side on dev, is it also fixed on your side?

https://user-images.githubusercontent.com/93608357/217604737-77f09e86-cb94-43b0-bf36-ec6b057e26bf.mp4

**Comment by tooshel** [comment]
Still seeing the same with the latest and a new user.
![image](https://user-images.githubusercontent.com/223338/217618476-875403cf-8546-4885-8dd4-f144a90c44d0.png)
